### ISSUE TITLE
Curl command downloads an empty gpdb file

### ISSUE THREAD

**Issue by pandikirushnan** [greenplum-db/go-gpdb#37]
curl -s https://api.github.com/repos/pivotal-gss/go-gpdb/releases/latest| grep "browser_download_url.*gpdb"| grep -v "browser_download_url.*datalab"     | cut -d : -f 2,3 | tr -d \"| wget -qi - -O gpdb
azureuser@zk1:~$ ls -lrth gpdb
-rw-rw-r-- 1 azureuser azureuser **0 Dec 10 10:32 gpdb**

**Comment by faisaltheparttimecoder** [comment]
thanks @pandikirushnan for reporting this issue is now fixed.. 

https://github.com/greenplum-db/go-gpdb/commit/7fb4a57a6b8a92001b5872df00407a0116cb0ce8
