### ISSUE TITLE
Add support for ubuntu release

### ISSUE THREAD

**Issue by DoubleDi** [greenplum-db/go-gpdb#40]
Hi! Awesome tool! 
What do you think of adding a --ubuntu flag to gpdb so we can install on ubuntu fast and easy

**Comment by faisaltheparttimecoder** [comment]
Hello @DoubleDi , Thank you :) 

I didn't get your request, Would it be possible to provide more information on 

- What is the current issue with ubuntu using gpdb? 
- Is it failing or erroring out ? 
- Or what is the flag you recommended is planned to do.

Faisal

**Comment by DoubleDi** [comment]
@faisaltheparttimecoder  Sorry for the inconvenience. 
Currently when you do gpdb download --install it will download and install the Centos version of greenplum and try to install it via yum. 
But we are using greenplum on ubuntu, so, unfortunately, can't use this tool.
Maybe you can adopt gpdb to work for ubuntu when you specify a flag --ubuntu, not to break current tool API?

**Comment by faisaltheparttimecoder** [comment]
I see the request.. Going to have it placed under feature request

+ This request will need logic to download the product of ubuntu ( easy )
+ Then use that ubuntu to install via apt-get (Need to change at multiple places)

**Comment by DoubleDi** [comment]
Whould be great to have in this tool, as greenplum is offered for both Ubuntu and Centos.

**Comment by faisaltheparttimecoder** [comment]
done https://github.com/greenplum-db/go-gpdb/commit/a77d1275c7f4266d079ee9254598e89d90fbc4a0
