### ISSUE TITLE
Unable to download v7.0.0.beta.0 (RHEL/CentOS 7 no longer supported)

### ISSUE THREAD

**Issue by chewygranola** [greenplum-db/go-gpdb#49]
Looks like download fails because tool is currently hardcoded to look for RHEL 7 link, which does not exist for GP7 (since RHEL/CentOS 7 is no longer supported).

Was able to get a preliminary version working on bento/rockylinux-8.7 that can download and install GP6 successfully. I'll check download/install of GP7 next.

**Comment by tbozzio** [comment]
FYI @chewygranola ,

I hit a subsequent issue with the install on CentOS Linux release 8.5.2111

https://github.com/greenplum-db/go-gpdb/issues/50

**Comment by chewygranola** [comment]
Mentioned in issue #50 — [pre-release](https://github.com/greenplum-db/go-gpdb/releases/tag/v4-beta.0) version linked works with bento/rockylinux8.7.
